version: '3.9'
networks:
  smr-network:
    driver: bridge
services:
  currency-exchange-service:
    image: seanmayerz/smr-currency-exchange-service:0.0.1-SNAPSHOT
    ports:
      - 8000:8000
    mem_limit: 512m
    environment:
      - JAVA_OPTS=-Dserver.port=8000
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://naming-server:8761/eureka/
    depends_on:
      - naming-server
    networks:
      - smr-network
  naming-server:
    container_name: naming-server
    image: seanmayerz/smr-naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    mem_limit: 512m
    networks:
      - smr-network
  currency-conversion-service:
    image: seanmayerz/smr-currency-conversion-service:0.0.1-SNAPSHOT
    ports:
      - 8100:8100
    mem_limit: 512m
    networks:
      - smr-network
    environment:
      - JAVA_OPTS=-Dserver.port=8100
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://naming-server:8761/eureka/
  api-gateway:
    image: seanmayerz/smr-api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    mem_limit: 512m
    networks:
      - smr-network
    environment:
      - JAVA_OPTS=-Dserver.port=8765
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://naming-server:8761/eureka/

