apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"containers":[{"name":"smr-currency-conversion-service-kubernetes"}]},"output":{"containers":[{"limits":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"name":"smr-currency-conversion-service-kubernetes"}]},"modified":true}'
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-conversion-kubernetes
  name: currency-conversion-kubernetes
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion-kubernetes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion-kubernetes
    spec:
      containers:
      - image: seanmayerz/smr-currency-conversion-service-kubernetes:0.0.2-SNAPSHOT
        env:
          - name: CURRENCY_EXCHANGE_URI
            value: http://currency-exchange-kubernetes
        imagePullPolicy: IfNotPresent
        name: smr-currency-conversion-service-kubernetes
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
      restartPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
---

  apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cloud.google.com/neg: '{"ingress":true}'
    labels:
      app: currency-conversion-kubernetes
    name: currency-conversion-kubernetes
    namespace: default
  spec:
    allocateLoadBalancerNodePorts: true
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
    selector:
      app: currency-conversion-kubernetes
    sessionAffinity: None
    type: LoadBalancer